# Copyright (c) HashiCorp, Inc.
---
repos:
    - repo: meta
      hooks:
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
            exclude: ^$
          - id: detect-private-key
            exclude: ^internal/provider/(client_test\.go|.*_test\.go)$
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: no-commit-to-branch
            args: [--branch, development, --branch, production]
          - id: trailing-whitespace
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.0
      hooks:
          - id: go-fmt
          - id: go-vet
            exclude: ^tools/
          - id: golangci-lint
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@3.4.2
            exclude: ^docs/
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.37.1
      hooks:
          - id: yamllint
            args: []
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.99.5
      hooks:
          - id: terraform_fmt
            args:
                - --hook-config=--tf-path=tofu
